apiVersion: skaffold/v1
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: bharatrose1/pasal-auth
      context: pasal-auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src : 'src/**/*.ts'
            dest: .
    - image: bharatrose1/pasal-product
      context: pasal-product
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src : 'src/**/*.ts'
            dest: .
    - image: bharatrose1/pasal-order
      context: pasal-order
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src : 'src/**/*.ts'
            dest: .
    - image: bharatrose1/pasal-static-server
      context: pasal-frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src : '**/*.{js,tsx,ts}'
            dest: .