apiVersion: apps/v1
kind: Deployment
metadata:
  name: pasal-product-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pasal-product
  template:
    metadata:
      labels:
        app: pasal-product
    spec:
      containers:
        - name: pasal-product
          image: bharatrose1/pasal-product
          env:
            - name: MONGO_URI
              value: 'mongodb://pasal-product-mongo-srv:27017/product'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RABBIT_MQ_URL
              value: 'amqp://rabbitmq-srv:5672'
---
apiVersion: v1
kind: Service 
metadata:
  name: pasal-product-srv
spec:
  selector:
    app: pasal-product
  ports:
    - name: pasal-product
      protocol: TCP
      port: 3000
      targetPort: 3000
#  'mongodb://pasal-product-mongo-srv:27017/product'